services:
  app:
    image: auth-service:latest
    container_name: auth-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/commerce-auth
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
    ports:
      - "8089:8089"
    networks:
      - commerce-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8089/actuator/health/liveness"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s

networks:
  commerce-net:
    external: true
